server:
  port: 8080

spring:
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:13306/dev
    username: dev
    password: dev
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 5
      minimum-idle: 2
      leak-detection-threshold: 15000

doma:
  dialect: mysql

logging:
  level:
    root: info
    web: trace
    com.gitlab.gn5r.uhbrhs: debug
  charset:
    console: UTF-8